import "../style/globals.scss";

import { ReduxProvider } from "../store/redux-provider";

import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";

// import { useSelector, useDispatch } from "react-redux";

// export function generateStaticParams() {
//    return [{ locale: "en" }, { locale: "ko" }];
// }

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
   const locale = "en";

   // const isDarkTheme = useSelector((state) => state.bic.isDarkTheme);

   let messages;
   try {
      messages = (await import(`../messages/${locale}.json`)).default;
   } catch (error) {
      notFound();
   }

   return (
      <ReduxProvider>
         <html lang={locale}>
            <body>
               <NextIntlClientProvider locale={locale} messages={messages}>
                  {children}
               </NextIntlClientProvider>
            </body>
         </html>
      </ReduxProvider>
   );
}
