import "../../style/globals.scss";

import { Providers as ReduxProvider } from "../../redux/providers";

import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";

export function generateStaticParams() {
   return [{ locale: "en" }, { locale: "ko" }];
}

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default async function RootLayout({ children, params: { locale } }) {
   let messages;
   try {
      messages = (await import(`../../messages/${locale}.json`)).default;
   } catch (error) {
      notFound();
   }

   return (
      <ReduxProvider>
         <html lang={locale}>
            <body>
               <NextIntlClientProvider locale={locale} messages={messages}>
                  {children}
               </NextIntlClientProvider>
            </body>
         </html>
      </ReduxProvider>
   );
}
