import "../../style/globals.scss";

import { dir } from "i18next";

const languages = ["en", "ko"];

export async function generateStaticParams() {
   return languages.map((lng) => ({ lng }));
}

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

function RootLayout({ children, params: { lng } }) {
   return (
      // <Provider store={store}>
      <html lang={lng} dir={dir(lng)}>
         <body>{children}</body>
      </html>
      // </Provider>
   );
}

export default RootLayout;
